# deploy-fstab.yml
# Playbook für Ansible Semaphore: Fügt gezielt neue NFS‑Einträge zur /etc/fstab hinzu,
# belässt alle übrigen Zeilen unverändert und aktiviert sie sofort.
#
# Tipp: Passe die Liste `fstab_new_entries` im Semaphore‑Formular an, falls IPs, Pfade oder Optionen variieren.

---
- name: "Custom NFS Mounts in /etc/fstab verwalten"
  hosts: "{{ target | default('all') }}"  # Inventory‑Gruppe
  become: true
  gather_facts: false

  vars:
    fstab_dest: "/etc/fstab"
    fstab_owner: "root"
    fstab_group: "root"
    fstab_mode: "0644"

    # Einträge, die ergänzt bzw. aktualisiert werden sollen
    fstab_new_entries:
      - ""
      - "# Paperless-ngx Mount - TrueNAS Server"
      - "10.11.2.2:/mnt/nvme/Applications/paperless /mnt/paperless nfs4 defaults,_netdev,hard,intr,resvport,nfsvers=4.2,proto=tcp,rsize=1048576,wsize=1048576 0 0"
      - ""
      - "# Media Mounts - TrueNAS Server"
      - "10.11.2.2:/mnt/hdd/nvr /mnt/nvr nfs4 defaults,_netdev,noatime,nodiratime,rsize=1048576,wsize=1048576,async,nconnect=4 0 0"
      - "10.11.2.2:/mnt/hdd/data /mnt/arr-stack nfs4 defaults,_netdev,noatime,nodiratime,rsize=1048576,wsize=1048576,async,nconnect=4 0 0"
      - "10.11.2.2:/mnt/hdd/minio /mnt/minio nfs4 defaults,_netdev,noatime,nodiratime,rsize=1048576,wsize=1048576,async,nconnect=4 0 0"
      - ""

  tasks:
    - name: "Füge/aktualisiere Ansible‑Block in /etc/fstab"
      ansible.builtin.blockinfile:
        path: "{{ fstab_dest }}"
        block: |
          {% for line in fstab_new_entries %}{{ line }}
          {% endfor %}
        marker: "# === ANSIBLE MANAGED NFS ENTRIES: {mark} ==="
        create: true
        owner: "{{ fstab_owner }}"
        group: "{{ fstab_group }}"
        mode: "{{ fstab_mode }}"
        backup: true
      notify: Remount filesystems

  handlers:
    - name: "Remount filesystems"
      ansible.builtin.command: "mount -a"
      changed_when: false